repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        entry: uv run --frozen pyright
        pass_filenames: false
        always_run: true
        types_or: [python, pyi]
