site_name: EOPF GeoZarr Data Model
site_description: Documentation for the EOPF GeoZarr library - converting EOPF datasets to GeoZarr format
site_author: Development Seed
repo_url: https://github.com/eopf-explorer/data-model
edit_uri: edit/main/docs/
site_url: https://eopf-explorer.github.io/

theme:
  name: material
  logo: assets/logo-eopf-sentinel-explorer-dark-icon.png
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eopf-explorer/data-model

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - User Guide: converter.md
  - API Reference: api-reference.md
  - Examples: examples.md
  - Architecture: architecture.md
  - GeoZarr Mini Spec: geozarr-minispec.md
  - Pydantic models: 
      - Sentinel1: models/sentinel1.md
      - Sentinel2: models/sentinel2.md
  - GeoZarr Specification: geozarr-specification-contribution.md
  - FAQ: faq.md
