name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # release-please creates releases and version bump commits
      pull-requests: write  # release-please opens and updates release PRs
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v4
        with:
          config-file: "release-please-config.json"
          manifest-file: ".release-please-manifest.json"